### ISSUE TITLE
Should “bytes” values be base64 encoded?

### ISSUE THREAD

**Issue by cwalther** [Sannis/protobuf2json-c#9]
https://developers.google.com/protocol-buffers/docs/proto3#json specifies that values of protobuf type “bytes” are encoded as base64 strings in the JSON representation. protobuf2json-c [encodes](https://github.com/Sannis/protobuf2json-c/blob/7b73232d265c8481040098ace9bbda69debcde91/src/protobuf2json.c#L133)/[decodes](https://github.com/Sannis/protobuf2json-c/blob/7b73232d265c8481040098ace9bbda69debcde91/src/protobuf2json.c#L587) them as plain strings. Who is right?

(I suspect it must be the former, because in a strict implementation the latter would make it impossible to encode byte sequences that are not valid UTF-8.)

**Comment by cwalther** [comment]
Could this be a matter of protocol buffers language version? I can’t find any specification of the proto2 JSON representation. Is there one?

Assuming I were to implement the Base64 encoding, would I need to make sure it continues to behave as before for proto2 definitions? I’m not sure if that can even be detected.

**Comment by Sannis** [comment]
@cwalther sounds reasonable. There are no reference implementation of json serialization for proto2, so I can refer to proto3 docs.

**Comment by Sannis** [comment]
@cwalther released as v0.4.0.

**Comment by cwalther** [comment]
Wee, you’re quick, thanks! I had already implemented it myself, but hadn’t finished it into a pull request yet. I’ll give this a try.

**Comment by Sannis** [comment]
@cwalther any feedback / fixes are welcome!
